// WebGL Water - pool walls & floor (Unity 6 / URP port)
// The pool mesh is generated by the scene builder already in world coordinates:
// floor at y = -1, walls rising to y = 2/12, spanning x,z in [-1, 1].
Shader "WebGLWater/PoolWall"
{
    Properties
    {
        [Enum(UnityEngine.Rendering.CullMode)] _Cull ("Cull", Float) = 2 // Back
    }
    SubShader
    {
        Tags { "RenderType" = "Opaque" "Queue" = "Geometry" }
        Pass
        {
            Cull [_Cull]
            ZWrite On
            ZTest LEqual

            CGPROGRAM
            #pragma vertex vert
            #pragma fragment frag
            #pragma target 4.0
            #include "UnityCG.cginc"
            #include "WaterCommon.hlsl"

            struct appdata { float4 vertex : POSITION; };
            struct v2f
            {
                float4 pos      : SV_POSITION;
                float3 position : TEXCOORD0;
            };

            v2f vert(appdata v)
            {
                v2f o;
                o.position = v.vertex.xyz;
                o.pos = mul(UNITY_MATRIX_VP, float4(v.vertex.xyz, 1.0));
                return o;
            }

            fixed4 frag(v2f i) : SV_Target
            {
                float3 color = GetWallColor(i.position);
                float4 info = tex2D(_WaterTex, i.position.xz * 0.5 + 0.5);
                if (i.position.y < info.r) color *= UNDERWATER_COLOR * 1.2;
                return float4(color, 1.0);
            }
            ENDCG
        }
    }
}
