// WebGL Water - pool walls & floor (Unity 6 / URP port)
// The pool mesh is generated by the scene builder already in world coordinates:
// floor at y = -1, walls rising to y = 2/12, spanning x,z in [-1, 1].
// Keeps the original analytic look (GetWallColor: refracted-light diffuse, projected
// caustics, rim shadow) but is now a proper URP forward pass, so it also RECEIVES
// real shadows cast by interactable objects from the scene's directional light.
Shader "WebGLWater/PoolWall"
{
    Properties
    {
        [Enum(UnityEngine.Rendering.CullMode)] _Cull ("Cull", Float) = 2 // Back
        _ObjectShadowStrength ("Object Shadow Strength", Range(0,1)) = 0.6
    }
    SubShader
    {
        Tags { "RenderType"="Opaque" "Queue"="Geometry" "RenderPipeline"="UniversalPipeline" }
        Pass
        {
            Name "ForwardLit"
            Tags { "LightMode"="UniversalForward" }
            Cull [_Cull]
            ZWrite On
            ZTest LEqual

            HLSLPROGRAM
            #pragma vertex vert
            #pragma fragment frag
            #pragma target 4.0
            #pragma multi_compile _ _MAIN_LIGHT_SHADOWS _MAIN_LIGHT_SHADOWS_CASCADE
            #pragma multi_compile _ _MAIN_LIGHT_SHADOWS_SCREEN
            #pragma multi_compile_fragment _ _SHADOWS_SOFT

            #include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Core.hlsl"
            #include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Lighting.hlsl"
            // Analytic helpers (GetWallColor etc). Uses legacy tex2D/sampler2D, which
            // resolve via the auto-included HLSLSupport in URP HLSLPROGRAM blocks.
            #include "WaterCommon.hlsl"
            #include "WaterFog.hlsl"
            #include "WaterVolume.hlsl"

            #define UNDERWATER_WALL_BOOST 1.2 // walls read a touch brighter than the surface underwater

            float _ObjectShadowStrength;

            struct appdata { float4 vertex : POSITION; };
            struct v2f
            {
                float4 pos      : SV_POSITION;
                float3 position : TEXCOORD0; // POOL space, for the analytic wall look
                float3 worldPos : TEXCOORD1; // world space, for shadows + fog
            };

            v2f vert(appdata v)
            {
                v2f o;
                float3 poolPos = v.vertex.xyz;          // pool mesh authored in [-1,1]
                float3 worldPos = PoolToWorld(poolPos); // placed by the volume frame
                o.position = poolPos;
                o.worldPos = worldPos;
                o.pos = TransformWorldToHClip(worldPos);
                return o;
            }

            half4 frag(v2f i) : SV_Target
            {
                float3 color = GetWallColor(i.position);
                float4 info = tex2D(_WaterTex, i.position.xz * 0.5 + 0.5);
                if (i.position.y < info.r) color *= UNDERWATER_COLOR * UNDERWATER_WALL_BOOST;

                // receive real object shadows from the scene's directional light
                float4 shadowCoord = TransformWorldToShadowCoord(i.worldPos);
                Light mainLight = GetMainLight(shadowCoord);
                color *= lerp(1.0, mainLight.shadowAttenuation, _ObjectShadowStrength);

                // depth absorption (shared fog; pool surface sits at the volume centre's Y)
                color = ApplyWaterFog(color, WaterPathLength(i.worldPos, _WorldSpaceCameraPos, _VolumeCenter.y));

                return half4(color, 1);
            }
            ENDHLSL
        }
    }
}
